# Generated by Django 4.1.5 on 2023-02-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCafeReview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeteria',
            name='puntajeAmbiente',
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='nombreReviewer',
            field=models.CharField(default='', max_length=30),
        ),
    ]
