# Generated by Django 4.1.5 on 2023-03-13 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCafeReview', '0002_remove_cafeteria_puntajeambiente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCafeReview.reviewer')),
            ],
        ),
    ]
