# Generated by Django 4.1.5 on 2023-03-16 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCafeReview', '0003_avatarreviewer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvatarReviewer',
            new_name='Avatar',
        ),
        migrations.RenameField(
            model_name='avatar',
            old_name='reviewer',
            new_name='user',
        ),
    ]
